apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskhive
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/taskhive"
  DB_USERNAME: "taskhive"
  CACHE_TYPE: "redis"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CORS_ORIGINS: "http://taskhive.local"
  OLLAMA_URL: "http://ollama:11434"
